// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microservice.proto

package com.joshuating.grpc;

public final class MicroserviceProto {
  private MicroserviceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CheckStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CheckStatusRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * can be used by the microservice to validate request
     * </pre>
     *
     * <code>uint64 regKey = 1;</code>
     * @return The regKey.
     */
    long getRegKey();

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code CheckStatusRequest}
   */
  public static final class CheckStatusRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CheckStatusRequest)
      CheckStatusRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckStatusRequest.newBuilder() to construct.
    private CheckStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckStatusRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckStatusRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckStatusRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              regKey_ = input.readUInt64();
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.joshuating.grpc.MicroserviceProto.CheckStatusRequest.class, com.joshuating.grpc.MicroserviceProto.CheckStatusRequest.Builder.class);
    }

    public static final int REGKEY_FIELD_NUMBER = 1;
    private long regKey_;
    /**
     * <pre>
     * can be used by the microservice to validate request
     * </pre>
     *
     * <code>uint64 regKey = 1;</code>
     * @return The regKey.
     */
    @java.lang.Override
    public long getRegKey() {
      return regKey_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (regKey_ != 0L) {
        output.writeUInt64(1, regKey_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (regKey_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, regKey_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.joshuating.grpc.MicroserviceProto.CheckStatusRequest)) {
        return super.equals(obj);
      }
      com.joshuating.grpc.MicroserviceProto.CheckStatusRequest other = (com.joshuating.grpc.MicroserviceProto.CheckStatusRequest) obj;

      if (getRegKey()
          != other.getRegKey()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REGKEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRegKey());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.joshuating.grpc.MicroserviceProto.CheckStatusRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CheckStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CheckStatusRequest)
        com.joshuating.grpc.MicroserviceProto.CheckStatusRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.joshuating.grpc.MicroserviceProto.CheckStatusRequest.class, com.joshuating.grpc.MicroserviceProto.CheckStatusRequest.Builder.class);
      }

      // Construct using com.joshuating.grpc.MicroserviceProto.CheckStatusRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        regKey_ = 0L;

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusRequest_descriptor;
      }

      @java.lang.Override
      public com.joshuating.grpc.MicroserviceProto.CheckStatusRequest getDefaultInstanceForType() {
        return com.joshuating.grpc.MicroserviceProto.CheckStatusRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.joshuating.grpc.MicroserviceProto.CheckStatusRequest build() {
        com.joshuating.grpc.MicroserviceProto.CheckStatusRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.joshuating.grpc.MicroserviceProto.CheckStatusRequest buildPartial() {
        com.joshuating.grpc.MicroserviceProto.CheckStatusRequest result = new com.joshuating.grpc.MicroserviceProto.CheckStatusRequest(this);
        result.regKey_ = regKey_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.joshuating.grpc.MicroserviceProto.CheckStatusRequest) {
          return mergeFrom((com.joshuating.grpc.MicroserviceProto.CheckStatusRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.joshuating.grpc.MicroserviceProto.CheckStatusRequest other) {
        if (other == com.joshuating.grpc.MicroserviceProto.CheckStatusRequest.getDefaultInstance()) return this;
        if (other.getRegKey() != 0L) {
          setRegKey(other.getRegKey());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.joshuating.grpc.MicroserviceProto.CheckStatusRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.joshuating.grpc.MicroserviceProto.CheckStatusRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long regKey_ ;
      /**
       * <pre>
       * can be used by the microservice to validate request
       * </pre>
       *
       * <code>uint64 regKey = 1;</code>
       * @return The regKey.
       */
      @java.lang.Override
      public long getRegKey() {
        return regKey_;
      }
      /**
       * <pre>
       * can be used by the microservice to validate request
       * </pre>
       *
       * <code>uint64 regKey = 1;</code>
       * @param value The regKey to set.
       * @return This builder for chaining.
       */
      public Builder setRegKey(long value) {
        
        regKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * can be used by the microservice to validate request
       * </pre>
       *
       * <code>uint64 regKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegKey() {
        
        regKey_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CheckStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:CheckStatusRequest)
    private static final com.joshuating.grpc.MicroserviceProto.CheckStatusRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.joshuating.grpc.MicroserviceProto.CheckStatusRequest();
    }

    public static com.joshuating.grpc.MicroserviceProto.CheckStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<CheckStatusRequest>() {
      @java.lang.Override
      public CheckStatusRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckStatusRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckStatusRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckStatusRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.joshuating.grpc.MicroserviceProto.CheckStatusRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CheckStatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <pre>
     * ** first 2 bits reserved for following
     * 0 / b00 - up and healthy
     * 1 / b01 - starting up
     * 2 / b10 - shutting down
     * 3 / b11 - error or unknown state
     * ** remaining bits only used to show activity and only applies to b00 
     * </pre>
     *
     * <code>string err = 2;</code>
     * @return The err.
     */
    java.lang.String getErr();
    /**
     * <pre>
     * ** first 2 bits reserved for following
     * 0 / b00 - up and healthy
     * 1 / b01 - starting up
     * 2 / b10 - shutting down
     * 3 / b11 - error or unknown state
     * ** remaining bits only used to show activity and only applies to b00 
     * </pre>
     *
     * <code>string err = 2;</code>
     * @return The bytes for err.
     */
    com.google.protobuf.ByteString
        getErrBytes();
  }
  /**
   * Protobuf type {@code CheckStatusResponse}
   */
  public static final class CheckStatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CheckStatusResponse)
      CheckStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckStatusResponse.newBuilder() to construct.
    private CheckStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckStatusResponse() {
      err_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckStatusResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckStatusResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              err_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.joshuating.grpc.MicroserviceProto.CheckStatusResponse.class, com.joshuating.grpc.MicroserviceProto.CheckStatusResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int ERR_FIELD_NUMBER = 2;
    private volatile java.lang.Object err_;
    /**
     * <pre>
     * ** first 2 bits reserved for following
     * 0 / b00 - up and healthy
     * 1 / b01 - starting up
     * 2 / b10 - shutting down
     * 3 / b11 - error or unknown state
     * ** remaining bits only used to show activity and only applies to b00 
     * </pre>
     *
     * <code>string err = 2;</code>
     * @return The err.
     */
    @java.lang.Override
    public java.lang.String getErr() {
      java.lang.Object ref = err_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        err_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ** first 2 bits reserved for following
     * 0 / b00 - up and healthy
     * 1 / b01 - starting up
     * 2 / b10 - shutting down
     * 3 / b11 - error or unknown state
     * ** remaining bits only used to show activity and only applies to b00 
     * </pre>
     *
     * <code>string err = 2;</code>
     * @return The bytes for err.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrBytes() {
      java.lang.Object ref = err_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        err_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!getErrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, err_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!getErrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, err_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.joshuating.grpc.MicroserviceProto.CheckStatusResponse)) {
        return super.equals(obj);
      }
      com.joshuating.grpc.MicroserviceProto.CheckStatusResponse other = (com.joshuating.grpc.MicroserviceProto.CheckStatusResponse) obj;

      if (getStatus()
          != other.getStatus()) return false;
      if (!getErr()
          .equals(other.getErr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.joshuating.grpc.MicroserviceProto.CheckStatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CheckStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CheckStatusResponse)
        com.joshuating.grpc.MicroserviceProto.CheckStatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.joshuating.grpc.MicroserviceProto.CheckStatusResponse.class, com.joshuating.grpc.MicroserviceProto.CheckStatusResponse.Builder.class);
      }

      // Construct using com.joshuating.grpc.MicroserviceProto.CheckStatusResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;

        err_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.joshuating.grpc.MicroserviceProto.internal_static_CheckStatusResponse_descriptor;
      }

      @java.lang.Override
      public com.joshuating.grpc.MicroserviceProto.CheckStatusResponse getDefaultInstanceForType() {
        return com.joshuating.grpc.MicroserviceProto.CheckStatusResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.joshuating.grpc.MicroserviceProto.CheckStatusResponse build() {
        com.joshuating.grpc.MicroserviceProto.CheckStatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.joshuating.grpc.MicroserviceProto.CheckStatusResponse buildPartial() {
        com.joshuating.grpc.MicroserviceProto.CheckStatusResponse result = new com.joshuating.grpc.MicroserviceProto.CheckStatusResponse(this);
        result.status_ = status_;
        result.err_ = err_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.joshuating.grpc.MicroserviceProto.CheckStatusResponse) {
          return mergeFrom((com.joshuating.grpc.MicroserviceProto.CheckStatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.joshuating.grpc.MicroserviceProto.CheckStatusResponse other) {
        if (other == com.joshuating.grpc.MicroserviceProto.CheckStatusResponse.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getErr().isEmpty()) {
          err_ = other.err_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.joshuating.grpc.MicroserviceProto.CheckStatusResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.joshuating.grpc.MicroserviceProto.CheckStatusResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object err_ = "";
      /**
       * <pre>
       * ** first 2 bits reserved for following
       * 0 / b00 - up and healthy
       * 1 / b01 - starting up
       * 2 / b10 - shutting down
       * 3 / b11 - error or unknown state
       * ** remaining bits only used to show activity and only applies to b00 
       * </pre>
       *
       * <code>string err = 2;</code>
       * @return The err.
       */
      public java.lang.String getErr() {
        java.lang.Object ref = err_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          err_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ** first 2 bits reserved for following
       * 0 / b00 - up and healthy
       * 1 / b01 - starting up
       * 2 / b10 - shutting down
       * 3 / b11 - error or unknown state
       * ** remaining bits only used to show activity and only applies to b00 
       * </pre>
       *
       * <code>string err = 2;</code>
       * @return The bytes for err.
       */
      public com.google.protobuf.ByteString
          getErrBytes() {
        java.lang.Object ref = err_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          err_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ** first 2 bits reserved for following
       * 0 / b00 - up and healthy
       * 1 / b01 - starting up
       * 2 / b10 - shutting down
       * 3 / b11 - error or unknown state
       * ** remaining bits only used to show activity and only applies to b00 
       * </pre>
       *
       * <code>string err = 2;</code>
       * @param value The err to set.
       * @return This builder for chaining.
       */
      public Builder setErr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        err_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ** first 2 bits reserved for following
       * 0 / b00 - up and healthy
       * 1 / b01 - starting up
       * 2 / b10 - shutting down
       * 3 / b11 - error or unknown state
       * ** remaining bits only used to show activity and only applies to b00 
       * </pre>
       *
       * <code>string err = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErr() {
        
        err_ = getDefaultInstance().getErr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ** first 2 bits reserved for following
       * 0 / b00 - up and healthy
       * 1 / b01 - starting up
       * 2 / b10 - shutting down
       * 3 / b11 - error or unknown state
       * ** remaining bits only used to show activity and only applies to b00 
       * </pre>
       *
       * <code>string err = 2;</code>
       * @param value The bytes for err to set.
       * @return This builder for chaining.
       */
      public Builder setErrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        err_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CheckStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:CheckStatusResponse)
    private static final com.joshuating.grpc.MicroserviceProto.CheckStatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.joshuating.grpc.MicroserviceProto.CheckStatusResponse();
    }

    public static com.joshuating.grpc.MicroserviceProto.CheckStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckStatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<CheckStatusResponse>() {
      @java.lang.Override
      public CheckStatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckStatusResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckStatusResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckStatusResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.joshuating.grpc.MicroserviceProto.CheckStatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckStatusRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckStatusRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckStatusResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022microservice.proto\"7\n\022CheckStatusReque" +
      "st\022\016\n\006regKey\030\001 \001(\004\022\021\n\ttimestamp\030\002 \001(\003\"2\n" +
      "\023CheckStatusResponse\022\016\n\006status\030\001 \001(\005\022\013\n\003" +
      "err\030\002 \001(\t2O\n\023MicroserviceService\0228\n\013Chec" +
      "kStatus\022\023.CheckStatusRequest\032\024.CheckStat" +
      "usResponseBF\n\023com.joshuating.grpcB\021Micro" +
      "serviceProtoZ\034proto_generated/microservi" +
      "ceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CheckStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckStatusRequest_descriptor,
        new java.lang.String[] { "RegKey", "Timestamp", });
    internal_static_CheckStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CheckStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckStatusResponse_descriptor,
        new java.lang.String[] { "Status", "Err", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
